/*
 Pathfinding Logic Overview

 Dijkstra’s Algorithm — compute_distances():
 ------------------------------------------
 This function implements Dijkstra’s algorithm to compute the shortest path
 from a given start node to all other nodes in the graph. It uses a min-heap
 (priority queue) to always expand the node with the smallest known distance.

 For each visited node, all outgoing edges are checked, and neighbor distances
 are updated if a shorter path is found. The process continues until all nodes
 have been processed or the queue is empty.

 The function returns:
 - A vector of minimum distances from the start node to all others.
 - A map of predecessors used to reconstruct shortest paths.

 Path Reconstruction — findPath():
 ---------------------------------
 This function rebuilds the shortest path from a start node to a goal node
 using the predecessor map generated by Dijkstra’s algorithm. It traces the
 path backward from the goal to the start and then reverses it to produce the
 correct order.

 If no path exists between the start and goal nodes, an empty path and a cost
 of -1 are returned.
 */

#include <Rcpp.h>

#include <cmath>
#include <limits>
#include <algorithm>

#include "myomp.h"
#include "GraphBuilder.h"
#include "Graph.h"

// Type aliases for clarity
using GraphPtr = Rcpp::XPtr<Graph>;
using GraphCache = std::pair<DistanceVector, PredecessorMap>;
using DF = Rcpp::DataFrame;

// ---------------------------------------------------------
// R wrappers
// ---------------------------------------------------------

SEXP build_semantic_graph(DF dec, DF target, DF gnd, DF master_seed, Rcpp::List params)
{
  if (!params.containsElementNamed("path_finder")) Rcpp::stop("Invalid parameters");
  Rcpp::List p = params["path_finder"];
  if (!p.containsElementNamed("k_neighborhood_connectivity")) Rcpp::stop("Invalid parameters");
  if (!p.containsElementNamed("max_gap")) Rcpp::stop("Invalid parameters");

  int k = Rcpp::as<int>(p["k_neighborhood_connectivity"]);
  double max_gap = Rcpp::as<double>(p["max_gap"]);

  GraphBuilder builder;
  builder.k = k;
  builder.max_gap = max_gap;

  PointCloud core(dec);
  PointCloud targets(target);
  PointCloud ground(gnd);
  PointCloud master(master_seed);

  builder.add_core_layer(core);
  builder.add_target_layer(core, targets);
  builder.add_seed_layer(core, ground);
  builder.add_master_seed_layer(ground, master);

  GraphPtr ptr(builder.get_graph(), true);
  return ptr;
}

SEXP build_instance_graph(DF dec, DF seed, DF master_seed, Rcpp::List params)
{
  // We are expecting a column foliage
  if (!dec.containsElementNamed("foliage")) Rcpp::stop("No wood/foliage segmentation found");
  Rcpp::IntegerVector foliage = dec["foliage"];

  // Extract parameters
  if (!params.containsElementNamed("path_finder")) Rcpp::stop("Invalid parameters");
  Rcpp::List p = params["path_finder"];
  if (!p.containsElementNamed("k_neighborhood_connectivity")) Rcpp::stop("Invalid parameters");
  if (!p.containsElementNamed("max_gap")) Rcpp::stop("Invalid parameters");
  int k = Rcpp::as<int>(p["k_neighborhood_connectivity"]);
  double max_gap = Rcpp::as<double>(p["max_gap"]);

  // Convert foliage column to vector<bool>
  std::vector<bool> wood; wood.reserve(foliage.size());
  for (int i = 0; i < foliage.size(); ++i) wood.push_back(foliage[i] == 0);

  GraphBuilder builder;
  builder.k = k;
  builder.max_gap = max_gap;
  builder.set_wood(wood);

  PointCloud core(dec);
  PointCloud seeds(seed);
  PointCloud master(master_seed);

  builder.add_core_layer(core);
  builder.add_seed_layer(core, seeds);
  builder.add_master_seed_layer(seeds, master);

  GraphPtr ptr(builder.get_graph(), true);
  return ptr;
}


/*
 *  For a start_node (expected master seed id) and a set of target nodes.
 *  Accumulate for each node the number of passage by the nodes to reach
 *  all target nodes from start node
 */
Rcpp::IntegerVector accumulate_passages(SEXP graph_ptr, int start_node, Rcpp::IntegerVector goal_nodes, int num_points)
{
  GraphPtr graph(graph_ptr);
  const int n_goals = goal_nodes.size();

  // Global count vector
  std::vector<int> passage(num_points, 0);

  // Precompute distances for fast access
  GraphCache cache = graph->compute_distances(start_node);

  // Parallel loop over goal nodes
  #pragma omp parallel
  {
    std::vector<int> local_passage(num_points, 0);  // thread-local counts

    #pragma omp for schedule(dynamic, 100)
    for (int i = 0; i < n_goals; ++i)
    {
      NodeId goal  = goal_nodes[i];

      auto [path, cost] = graph->findPath(start_node, goal, cache);

      for (size_t j = 0; j < path.size(); ++j)
      {
        NodeId id = path[j];
        if (id >= 0 && id < num_points)
          local_passage[id] += 1;
      }
    }

    // Merge results into global passage safely
    #pragma omp critical
    {
      for (int i = 0; i < num_points; ++i)
        passage[i] += local_passage[i];
    }
  }

  return Rcpp::wrap(passage);
}

/*
 * For a set query nodes (usually seed nodes) computes for each node of the graph
 * the distance to the closest query node and return the id of the
 * closest nodes
 */
Rcpp::IntegerVector find_closest_node(SEXP graph_ptr, Rcpp::IntegerVector ids)
{
  GraphPtr graph(graph_ptr);

  // Convert R vector of ground nodes to std::vector<NodeId>
  NodeIDs node_ids(ids.begin(), ids.end());

  std::vector<double> distances;
  NodeIDs closest_nodeids;

  // Run the optimized multi-source Dijkstra
  graph->shortest_paths_from_node(node_ids, distances, closest_nodeids);

  // Return as R list
  return Rcpp::IntegerVector(closest_nodeids.begin(), closest_nodeids.end());
}
