/*
 Pathfinding Logic Overview

 Dijkstra’s Algorithm — compute_distances():
 ------------------------------------------
 This function implements Dijkstra’s algorithm to compute the shortest path
 from a given start node to all other nodes in the graph. It uses a min-heap
 (priority queue) to always expand the node with the smallest known distance.

 For each visited node, all outgoing edges are checked, and neighbor distances
 are updated if a shorter path is found. The process continues until all nodes
 have been processed or the queue is empty.

 The function returns:
 - A vector of minimum distances from the start node to all others.
 - A map of predecessors used to reconstruct shortest paths.

 Path Reconstruction — findPath():
 ---------------------------------
 This function rebuilds the shortest path from a start node to a goal node
 using the predecessor map generated by Dijkstra’s algorithm. It traces the
 path backward from the goal to the start and then reverses it to produce the
 correct order.

 If no path exists between the start and goal nodes, an empty path and a cost
 of -1 are returned.
 */

#include <Rcpp.h>
#include "Graph.h"

// Type aliases for clarity in Rcpp bindings
using GraphPtr = Rcpp::XPtr<Graph>;
using PrecomputedData = std::unordered_map<NodeId, std::pair<DistanceVector, PredecessorMap>>;
using PrecomputedPtr = Rcpp::XPtr<PrecomputedData>;

// [[Rcpp::export]]
SEXP build_graph(Rcpp::DataFrame graph_df)
{
  Rcpp::IntegerVector from_nodes = graph_df["from"];
  Rcpp::IntegerVector to_nodes   = graph_df["to"];
  Rcpp::NumericVector edge_costs = graph_df["cost"];

  auto* g = new Graph(from_nodes.begin(), to_nodes.begin(), edge_costs.begin(), from_nodes.size());
  GraphPtr ptr(g, true);  // 'true' ensures auto-delete on garbage collection
  return ptr;
}

// [[Rcpp::export]]
SEXP compute_distances(SEXP graph_ptr, Rcpp::IntegerVector start_node_ids)
{
  GraphPtr graph(graph_ptr);
  auto* precomputed = new PrecomputedData();

  for (int start_node : start_node_ids)
  {
    precomputed->emplace(start_node, graph->compute_distances(start_node));
  }

  PrecomputedPtr pptr(precomputed, true);
  return pptr;
}

// [[Rcpp::export]]
Rcpp::List findPaths(SEXP graph_ptr,
                     SEXP precomputed_ptr,
                     Rcpp::IntegerVector start_node_ids,
                     Rcpp::IntegerVector goal_node_ids)
{
  GraphPtr graph(graph_ptr);
  PrecomputedPtr precomputed(precomputed_ptr);

  const int num_pairs = start_node_ids.size();
  Rcpp::List paths(num_pairs);
  Rcpp::NumericVector total_costs(num_pairs);

  for (int i = 0; i < num_pairs; ++i)
  {
    NodeId start = start_node_ids[i];
    NodeId goal  = goal_node_ids[i];

    const auto& data = precomputed->at(start);
    auto [path, cost] = graph->findPath(start, goal, data);

    paths[i] = path;
    total_costs[i] = cost;
  }

  return Rcpp::List::create(
    Rcpp::_["paths"] = paths,
    Rcpp::_["total_costs"] = total_costs
  );
}


