// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colMins
IntegerVector colMins(NumericMatrix mat);
RcppExport SEXP _lidRtls_colMins(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(colMins(mat));
    return rcpp_result_gen;
END_RCPP
}
// findPaths
Rcpp::List findPaths(Rcpp::DataFrame graph_df, Rcpp::IntegerVector start_node_ids, Rcpp::IntegerVector goal_node_ids);
RcppExport SEXP _lidRtls_findPaths(SEXP graph_dfSEXP, SEXP start_node_idsSEXP, SEXP goal_node_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph_df(graph_dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type start_node_ids(start_node_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type goal_node_ids(goal_node_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(findPaths(graph_df, start_node_ids, goal_node_ids));
    return rcpp_result_gen;
END_RCPP
}
// get_distance_matrix
Rcpp::NumericMatrix get_distance_matrix(Rcpp::DataFrame graph_df, Rcpp::IntegerVector start_node_ids, Rcpp::IntegerVector goal_node_ids);
RcppExport SEXP _lidRtls_get_distance_matrix(SEXP graph_dfSEXP, SEXP start_node_idsSEXP, SEXP goal_node_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph_df(graph_dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type start_node_ids(start_node_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type goal_node_ids(goal_node_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_distance_matrix(graph_df, start_node_ids, goal_node_ids));
    return rcpp_result_gen;
END_RCPP
}
// fit_circle_on_3_points_stl
std::vector<double> fit_circle_on_3_points_stl(const std::vector<std::vector<double>>& points_subset);
RcppExport SEXP _lidRtls_fit_circle_on_3_points_stl(SEXP points_subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type points_subset(points_subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_circle_on_3_points_stl(points_subset));
    return rcpp_result_gen;
END_RCPP
}
// fit_circle_stl
List fit_circle_stl(NumericMatrix points, int num_iterations, double inlier_threshold);
RcppExport SEXP _lidRtls_fit_circle_stl(SEXP pointsSEXP, SEXP num_iterationsSEXP, SEXP inlier_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type inlier_threshold(inlier_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_circle_stl(points, num_iterations, inlier_threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smooth3d
DataFrame cpp_smooth3d(S4 las, NumericVector radius, NumericVector weight, int ncpu, bool pgbar, bool verbose);
RcppExport SEXP _lidRtls_cpp_smooth3d(SEXP lasSEXP, SEXP radiusSEXP, SEXP weightSEXP, SEXP ncpuSEXP, SEXP pgbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type las(lasSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    Rcpp::traits::input_parameter< bool >::type pgbar(pgbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smooth3d(las, radius, weight, ncpu, pgbar, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lidRtls_colMins", (DL_FUNC) &_lidRtls_colMins, 1},
    {"_lidRtls_findPaths", (DL_FUNC) &_lidRtls_findPaths, 3},
    {"_lidRtls_get_distance_matrix", (DL_FUNC) &_lidRtls_get_distance_matrix, 3},
    {"_lidRtls_fit_circle_on_3_points_stl", (DL_FUNC) &_lidRtls_fit_circle_on_3_points_stl, 1},
    {"_lidRtls_fit_circle_stl", (DL_FUNC) &_lidRtls_fit_circle_stl, 3},
    {"_lidRtls_cpp_smooth3d", (DL_FUNC) &_lidRtls_cpp_smooth3d, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_lidRtls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
