// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_graph
SEXP build_graph(Rcpp::DataFrame graph_df);
RcppExport SEXP _lidRtls_build_graph(SEXP graph_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph_df(graph_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(build_graph(graph_df));
    return rcpp_result_gen;
END_RCPP
}
// compute_distances
SEXP compute_distances(SEXP graph_ptr, Rcpp::IntegerVector start_node_ids);
RcppExport SEXP _lidRtls_compute_distances(SEXP graph_ptrSEXP, SEXP start_node_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type graph_ptr(graph_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type start_node_ids(start_node_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_distances(graph_ptr, start_node_ids));
    return rcpp_result_gen;
END_RCPP
}
// findPaths
Rcpp::List findPaths(SEXP graph_ptr, SEXP precomputed_ptr, Rcpp::IntegerVector start_node_ids, Rcpp::IntegerVector goal_node_ids);
RcppExport SEXP _lidRtls_findPaths(SEXP graph_ptrSEXP, SEXP precomputed_ptrSEXP, SEXP start_node_idsSEXP, SEXP goal_node_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type graph_ptr(graph_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type precomputed_ptr(precomputed_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type start_node_ids(start_node_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type goal_node_ids(goal_node_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(findPaths(graph_ptr, precomputed_ptr, start_node_ids, goal_node_ids));
    return rcpp_result_gen;
END_RCPP
}
// C_voxel_barycenter_decimate
Rcpp::LogicalVector C_voxel_barycenter_decimate(Rcpp::NumericVector X, Rcpp::NumericVector Y, Rcpp::NumericVector Z, Rcpp::NumericVector id);
RcppExport SEXP _lidRtls_C_voxel_barycenter_decimate(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(C_voxel_barycenter_decimate(X, Y, Z, id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lidRtls_build_graph", (DL_FUNC) &_lidRtls_build_graph, 1},
    {"_lidRtls_compute_distances", (DL_FUNC) &_lidRtls_compute_distances, 2},
    {"_lidRtls_findPaths", (DL_FUNC) &_lidRtls_findPaths, 4},
    {"_lidRtls_C_voxel_barycenter_decimate", (DL_FUNC) &_lidRtls_C_voxel_barycenter_decimate, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lidRtls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
