# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_voxel_barycenter_decimate <- function(X, Y, Z, res) {
    .Call(`_arbor_C_voxel_barycenter_decimate`, X, Y, Z, res)
}

C_anisotropy <- function(df, k, ncpu = 1L) {
    .Call(`_arbor_C_anisotropy`, df, k, ncpu)
}

C_connected_component <- function(df, res, connectivity) {
    .Call(`_arbor_C_connected_component`, df, res, connectivity)
}

C_sor <- function(df, k, m, ncpu = 1L) {
    .Call(`_arbor_C_sor`, df, k, m, ncpu)
}

build_semantic_graph <- function(dec, target, gnd, master_seed, params) {
    .Call(`_arbor_build_semantic_graph`, dec, target, gnd, master_seed, params)
}

build_instance_graph <- function(dec, seed, master_seed, params) {
    .Call(`_arbor_build_instance_graph`, dec, seed, master_seed, params)
}

accumulate_passages <- function(graph_ptr, start_node, goal_nodes, num_points) {
    .Call(`_arbor_accumulate_passages`, graph_ptr, start_node, goal_nodes, num_points)
}

find_closest_node <- function(graph_ptr, ids) {
    .Call(`_arbor_find_closest_node`, graph_ptr, ids)
}

qsm_topology_cpp <- function(qsm) {
    .Call(`_arbor_qsm_topology_cpp`, qsm)
}

qsm_architecture_cpp <- function(qsm, root_id = 1L) {
    .Call(`_arbor_qsm_architecture_cpp`, qsm, root_id)
}

cpp_build_skeleton <- function(data, max_d) {
    .Call(`_arbor_cpp_build_skeleton`, data, max_d)
}

qsm_layers_cpp <- function(df, D) {
    .Call(`_arbor_qsm_layers_cpp`, df, D)
}

qsm_simplify_cpp <- function(qsm, max_length = 0.3) {
    .Call(`_arbor_qsm_simplify_cpp`, qsm, max_length)
}

qsm_write_cpp <- function(df, filename, binary) {
    invisible(.Call(`_arbor_qsm_write_cpp`, df, filename, binary))
}

qsm_smooth_cpp <- function(df, niter = 1L, th = 0) {
    .Call(`_arbor_qsm_smooth_cpp`, df, niter, th)
}

qsm_prolongation_cpp <- function(df, d, L = 0.1) {
    .Call(`_arbor_qsm_prolongation_cpp`, df, d, L)
}

qsm_measure_cpp <- function(pc, df) {
    .Call(`_arbor_qsm_measure_cpp`, pc, df)
}

qsm_polynomial_fitting_cpp <- function(df, tip_radius) {
    .Call(`_arbor_qsm_polynomial_fitting_cpp`, df, tip_radius)
}

qsm_reconstruction_cpp <- function(df, tip_radius) {
    .Call(`_arbor_qsm_reconstruction_cpp`, df, tip_radius)
}

read_adtree_skeleton <- function(filename) {
    .Call(`_arbor_read_adtree_skeleton`, filename)
}

