# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_graph <- function(graph_df) {
    .Call(`_lidRtls_build_graph`, graph_df)
}

compute_distances <- function(graph_ptr, start_node_ids) {
    .Call(`_lidRtls_compute_distances`, graph_ptr, start_node_ids)
}

findPaths <- function(graph_ptr, precomputed_ptr, start_node_ids, goal_node_ids) {
    .Call(`_lidRtls_findPaths`, graph_ptr, precomputed_ptr, start_node_ids, goal_node_ids)
}

C_voxel_barycenter_decimate <- function(X, Y, Z, id) {
    .Call(`_lidRtls_C_voxel_barycenter_decimate`, X, Y, Z, id)
}

